### PR TITLE
PlayerJS integration

### PR DESCRIPTION
**Pull request by alxjrvs**

### CODE REVIEW

**Comment by cqr** [comment]
Looks fine to me given the limitations you mentioned.

**Review by cqr — APPROVED** [review]

**Comment by cqr** [comment]
Wait, did the test harness fire on all cylinders?

**Comment by alxjrvs** [comment]
@chrisrhoden yep! I dropped the link for the embed player and it fired.

**Comment by alxjrvs** [comment]
http://playerjs.io/test.html?url=http%3A%2F%2Flocalhost%3A4300%2Fe%3Ftt%3DEp.%252052.%2520The%2520Suffering%2520Game%2520-%2520Chapter%2520Two%26ts%3DThe%2520Adventure%2520Zone%26tc%3D%26ua%3Dhttp%253A%252F%252Ftraffic.libsyn.com%252Fadventurezone%252FTheAdventureZone052.mp3%253Fdest-id%253D235309%26ui%3Dhttp%253A%252F%252Fstatic.libsyn.com%252Fp%252Fassets%252F7%252F4%252Ff%252Fd%252F74fdaa8be1b5684f%252FThe_Adventure_Zone_Flat.jpg%26uf%3Dhttp%253A%252F%252Fadventurezone.libsyn.com%252Frss%26uc%3D%26us%3Dhttp%253A%252F%252Fadventurezone.libsyn.com%252Frss%26gs%3D_blank < --- Should be the full link with local dev server running.

**Comment by cqr** [comment]
[embed player.js](https://trello.com/c/9jcuKIef/13-embed-player-js)

**Pull request merged**
